# Generated by Django 3.2 on 2023-12-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batchid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='client_company',
            fields=[
                ('clientid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('deliveryid', models.IntegerField(primary_key=True, serialize=False)),
                ('deliverydate', models.DateField()),
                ('deliverytime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='issuance',
            fields=[
                ('issuanceid', models.IntegerField(primary_key=True, serialize=False)),
                ('issuancedate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('srp', models.FloatField()),
                ('classification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='item_return',
            fields=[
                ('returnid', models.IntegerField(primary_key=True, serialize=False)),
                ('returndate', models.DateField()),
                ('batchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.batch')),
            ],
        ),
        migrations.CreateModel(
            name='item_transfer',
            fields=[
                ('transferid', models.IntegerField(primary_key=True, serialize=False)),
                ('transferdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sales_agent',
            fields=[
                ('agentid', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client_company')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplierid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_staff',
            fields=[
                ('staffid', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_item',
            fields=[
                ('transferitemid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemquantity', models.IntegerField()),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('transferid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item_transfer')),
            ],
        ),
        migrations.CreateModel(
            name='sales_invoice',
            fields=[
                ('invoiceid', models.IntegerField(primary_key=True, serialize=False)),
                ('invoicedate', models.DateField()),
                ('agentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sales_agent')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client_company')),
            ],
        ),
        migrations.CreateModel(
            name='return_item',
            fields=[
                ('returnitemid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemquantity', models.IntegerField()),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
                ('returnid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item_return')),
            ],
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='fromagentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromagent', to='dashboard.sales_agent'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='frombatchid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frombatch', to='dashboard.batch'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='toagentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toagent', to='dashboard.sales_agent'),
        ),
        migrations.AddField(
            model_name='item_transfer',
            name='tobatchid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tobatch', to='dashboard.batch'),
        ),
        migrations.AddField(
            model_name='item_return',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.warehouse_staff'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplierid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier'),
        ),
        migrations.CreateModel(
            name='issuance_item',
            fields=[
                ('issuanceitemid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemquantity', models.IntegerField()),
                ('issuanceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.issuance')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
            ],
        ),
        migrations.AddField(
            model_name='issuance',
            name='agentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sales_agent'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='batchid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.batch'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.warehouse_staff'),
        ),
        migrations.CreateModel(
            name='invoice_item',
            fields=[
                ('invoiceitemid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemquantity', models.IntegerField()),
                ('srp', models.FloatField()),
                ('discountrate', models.FloatField()),
                ('totalsales', models.FloatField()),
                ('invoiceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sales_invoice')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('discountid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('discountrate', models.FloatField()),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.client_company')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_item',
            fields=[
                ('deliveryitemid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemquantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('totalcost', models.FloatField()),
                ('deliveryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.delivery')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.warehouse_staff'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='supplierid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier'),
        ),
    ]
